# Generated by Django 2.1.4 on 2019-02-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='food', max_length=30, verbose_name='item')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('rate', models.SmallIntegerField(verbose_name='rate')),
                ('order', models.ManyToManyField(to='eats.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='Name of resulting restaurant', max_length=30, verbose_name='name')),
                ('address', models.CharField(help_text='Address of resulting restaurant', max_length=255, verbose_name='address')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('long', models.FloatField(verbose_name='long')),
                ('radius', models.FloatField(verbose_name='radius')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eats.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('results', models.ManyToManyField(to='eats.Result')),
            ],
        ),
    ]
